import numpy as np
import math
from numpy import matrix
from numpy import linalg

def modInv(a,p):
  """Finds the inverse of a mod p, if it exists"""
  for i in range(1,p):
    if (i*a)%p==1:
      return i
  raise ValueError(str(a)+" has no inverse mod "+str(p))

def minor(A,i,j):
  """Return matrix A with the ith row and jth column deleted"""
  A=np.array(A)
  minor=np.zeros(shape=(len(A)-1,len(A)-1))
  p=0
  for s in range(0,len(minor)):
    if p==i:
      p=p+1
    q=0
    for t in range(0,len(minor)):
      if q==j:
        q=q+1
      minor[s][t]=A[p][q]
      q=q+1
    p=p+1
  return minor

def modMatInv(A,p):
  """Finds the inverse of matrix A mod p"""
  n=len(A)
  A=matrix(A)
  adj=np.zeros(shape=(n,n))
  for i in range(0,n):
    for j in range(0,n):
      adj[i][j]=((-1)**(i+j)*int(round(linalg.det(minor(A,j,i)))))%p
  return (modInv(int(round(linalg.det(A))),p)*adj)%p


def circmat(V, M):
    """Creates a circulant matrix for the purposes of finding the length of the LSFR"""
    C = np.zeros((M, M))

    Vlen = len(V)
    if (Vlen< 2 * M -1):
        raise ValueError('The vector v needs to be atleast length 2m-1')
    for i in range(M):
        for j in range(M):
            C[i, j] = V[(i - j) % M]

    return C


def lsfrlength(V, N):
    """Tests a vector V to see if it is generated by a LSFR of at most length M"""
    for i in range(N):
        M=circmat(V, i)
        Mdet= np.linalg.det(M) % 2
        print(i, Mdet)
    return 

V2=101001101100010010000111000001011111100101010001100111101100100001110000010111111
#String of 1s and 0s is converted to an array to be used in our functions
V2List=list(map(int,str(V2)))
print(V2List)

lsfrlength(V2List, 10)
#The length of the recurrence is very likely to be 6

def lsfrsolve(V, N):
    """Given N, the assumed recurrence length, find the coeffecients of the recurrence"""
    Vln=len(V)
    M=circmat(V, N)
    Mdet= np.linalg.det(M)

    B=V[N:2*N] #Row N+1 column 2*N is what we will use to solve
    Minv= modMatInv(M, 2)

    C= np.dot(Minv, B) % 2 #Product of B and the M matrix mod 2 inverse
    print( 'The LSFR Recurrance coefficents are', C )
    return
    

lsfrsolve(V2List, 6)